# Generated by Django 2.2.5 on 2020-01-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Type Of Sample')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(blank=True, max_length=40, verbose_name='Composition')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='Date Added')),
                ('formula', models.CharField(blank=True, max_length=40, verbose_name='Formula')),
                ('grain_size', models.CharField(blank=True, max_length=40, verbose_name='Grain Size')),
                ('locality', models.TextField(blank=True, verbose_name='Locality')),
                ('min_reflectance', models.FloatField(blank=True, verbose_name='Minimum Reflectance')),
                ('sample_name', models.CharField(blank=True, max_length=40, verbose_name='Sample Name')),
                ('max_reflectance', models.FloatField(blank=True, verbose_name='Maximum Reflectance')),
                ('other', models.TextField(blank=True, verbose_name='Other Information')),
                ('references', models.TextField(blank=True, verbose_name='References')),
                ('reflectance', models.TextField(default='[0,0]', verbose_name='Reflectance')),
                ('resolution', models.CharField(blank=True, max_length=40, verbose_name='Resolution')),
                ('material_class', models.CharField(blank=True, max_length=40, verbose_name='Material Class')),
                ('sample_desc', models.TextField(blank=True, verbose_name='Sample Description')),
                ('sample_id', models.CharField(max_length=40, verbose_name='Sample ID')),
                ('view_geom', models.CharField(blank=True, max_length=40, verbose_name='Viewing Geometry')),
                ('image', models.CharField(blank=True, max_length=100, verbose_name='Path to Image')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mars.Database', verbose_name='Database of Origin')),
                ('sample_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mars.SampleType', verbose_name='Sample Type')),
            ],
            options={
                'ordering': ['sample_id'],
            },
        ),
    ]
