# Generated by Django 2.2.5 on 2020-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0002_filterset'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='illumination',
            field=models.TextField(blank=True),
        ),
    ]
