# Generated by Django 2.2.5 on 2020-01-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0003_filterset_illumination'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='filter_frequencies',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
