# Generated by Django 3.0.2 on 2020-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='filename',
            field=models.CharField(blank=True, max_length=80, verbose_name='Name of Uploaded File'),
        ),
        migrations.AddField(
            model_name='sample',
            name='import_notes',
            field=models.TextField(blank=True, verbose_name='File import notes'),
        ),
    ]
