# Generated by Django 3.0.2 on 2020-02-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0006_auto_20200128_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='sample',
            name='flagged',
            field=models.CharField(blank=True, max_length=10, verbose_name='Flag Status'),
        ),
    ]
