# Generated by Django 3.0.2 on 2020-02-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0007_auto_20200203_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='simulated_spectra',
            field=models.TextField(default='{}', verbose_name='Simulated Spectra'),
        ),
    ]
