# Generated by Django 3.0.2 on 2020-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0008_sample_simulated_spectra'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filterset',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='filterset',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
