# Generated by Django 3.1.4 on 2020-12-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0009_auto_20200207_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='library',
            field=models.ManyToManyField(to='mars.Library'),
        ),
    ]
