# Generated by Django 3.1.4 on 2020-12-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0011_auto_20201207_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='library',
            field=models.ManyToManyField(blank=True, to='mars.Library'),
        ),
    ]
