# Generated by Django 3.1.4 on 2020-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0013_remove_sample_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='released',
            field=models.BooleanField(default=False, verbose_name='Released to Public'),
        ),
    ]
