# Generated by Django 3.1.4 on 2020-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0015_filterset_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='released',
            field=models.BooleanField(default=False, verbose_name='Released to Public'),
        ),
    ]
