# Generated by Django 3.1.4 on 2020-12-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0016_database_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterset',
            old_name='citation',
            new_name='url',
        ),
    ]
