# Generated by Django 3.1.4 on 2020-12-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0018_auto_20201211_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='short_name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
