# Generated by Django 3.1.4 on 2020-12-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0019_auto_20201211_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='citation',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='url',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='display_order',
            field=models.IntegerField(blank=True, db_index=True, default=10000),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='filter_frequencies',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='filters',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='illumination',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='short_name',
            field=models.CharField(db_index=True, max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='url',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='filterset',
            name='wavelengths',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='composition',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_added',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='formula',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Formula'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='grain_size',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Grain Size'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Path to Image'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='import_notes',
            field=models.TextField(blank=True, db_index=True, verbose_name='File import notes'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='library',
            field=models.ManyToManyField(blank=True, db_index=True, to='mars.Library'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='locality',
            field=models.TextField(blank=True, db_index=True, verbose_name='Locality'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='max_reflectance',
            field=models.FloatField(blank=True, db_index=True, verbose_name='Maximum Reflectance'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='min_reflectance',
            field=models.FloatField(blank=True, db_index=True, verbose_name='Minimum Reflectance'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='other',
            field=models.TextField(blank=True, db_index=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='references',
            field=models.TextField(blank=True, db_index=True, verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='reflectance',
            field=models.TextField(db_index=True, default='[0,0]', verbose_name='Reflectance'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='resolution',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Resolution'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_desc',
            field=models.TextField(blank=True, db_index=True, verbose_name='Sample Description'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Sample ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Sample Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='simulated_spectra',
            field=models.TextField(db_index=True, default='{}', verbose_name='Simulated Spectra'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='view_geom',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Viewing Geometry'),
        ),
    ]
