name: visor
channels:
  - conda-forge
dependencies:
  - django
  - django-extensions
  - git
  - gunicorn
  - jupyter
  - marslab
  - numpy>=2.0.0
  - pip
  - whitenoise
  - pip:
      - django-mass-edit
