# Generated by Django 3.1.7 on 2021-02-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vnirsd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterset',
            old_name='filter_frequencies',
            new_name='filter_wavelengths',
        ),
    ]
