# Generated by Django 4.1.3 on 2022-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sample",
            name="sample_type",
        ),
        migrations.AddField(
            model_name="sample",
            name="sample_type",
            field=models.ManyToManyField(
                to="visor.sampletype", verbose_name="Sample Type"
            ),
        ),
    ]
