# Generated by Django 4.0.4 on 2022-12-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0002_remove_sample_sample_type_sample_sample_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='grain_size',
            new_name='grain_size_description',
        ),
    ]
