# Generated by Django 4.0.4 on 2022-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0003_rename_grain_size_sample_grain_size_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='grain_size',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Grain Size'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='grain_size_description',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Grain Size Description'),
        ),
    ]
