# Generated by Django 4.2.23 on 2025-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0004_sample_grain_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='collection_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data Collection Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_added',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Added to VISOR'),
        ),
    ]
