# Generated by Django 4.2.23 on 2025-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0004_sample_grain_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='date_added',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Added to VISOR'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Spectrum ID'),
        ),
    ]
