# Generated by Django 4.2.23 on 2025-07-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0005_sample_collection_date_alter_sample_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='collection_date',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(db_index=True, max_length=40, unique=True, verbose_name='Spectrum ID'),
        ),
    ]
