# Generated by Django 5.1.3 on 2026-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0005_alter_sample_date_added_alter_sample_sample_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='material_class',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Material Class'),
        ),
    ]
