# Generated by Django 5.2.14 on 2026-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0006_alter_sample_material_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='basename',
            field=models.TextField(blank=True, db_index=True, max_length=40, verbose_name='Basename'),
        ),
        migrations.AddField(
            model_name='sample',
            name='directory',
            field=models.TextField(blank=True, db_index=True, max_length=40, verbose_name='Directory'),
        ),
    ]
