# Generated by Django 5.2.14 on 2026-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visor', '0007_sample_basename_sample_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='approx_measured_area',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Approximate Measured Area'),
        ),
        migrations.AddField(
            model_name='sample',
            name='atmosphere',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Atmosphere'),
        ),
        migrations.AddField(
            model_name='sample',
            name='boxcar_zero_fill',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Boxcar/Zero Fill'),
        ),
        migrations.AddField(
            model_name='sample',
            name='depolarizer',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Depolarizer'),
        ),
        migrations.AddField(
            model_name='sample',
            name='integration_time',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Integration Time'),
        ),
        migrations.AddField(
            model_name='sample',
            name='light_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Light Source'),
        ),
        migrations.AddField(
            model_name='sample',
            name='number_of_spectrum_avg',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='# of Spectrum Avg '),
        ),
        migrations.AddField(
            model_name='sample',
            name='pickup_fiber',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Pickup Fiber'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_cup',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Sample Cup'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Sample #'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_prep',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Sample Prep'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_spun',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Sample Spun'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_temperature',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Sample Temperature'),
        ),
        migrations.AddField(
            model_name='sample',
            name='spectralon_correction_file',
            field=models.TextField(blank=True, db_index=True, max_length=300, verbose_name='Spectralon Correction File'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='basename',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Basename'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='directory',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Directory'),
        ),
    ]
